spring.application.name=rootLab

# MongoDB Atlas
spring.data.mongodb.uri=mongodb+srv://admin:admin@cluster0.afu07sh.mongodb.net/rootLabDB?retryWrites=true&w=majority

# Debug (optional)
spring.data.mongodb.auto-index-creation=true
logging.level.org.springframework.data.mongodb=DEBUG

server.port=8080